### ISSUE TITLE
Unable to install babel-runtime.

### ISSUE THREAD

**Issue by mdkshuvo** [meteor/localmarket#10]
![bable-1](https://user-images.githubusercontent.com/30826181/33058474-fc0e1438-ceb9-11e7-9310-3c263eac9af8.jpg)
![bable](https://user-images.githubusercontent.com/30826181/33058484-02bdf578-ceba-11e7-8f1d-a9243be5feff.jpg)

**Comment by abernix** [comment]
This isn't the right place for this issue.  Also, please don't go around posting the same question everywhere, as you've done with https://github.com/meteor/meteor/issues/6799#issuecomment-345930951 and https://github.com/meteor/meteor/issues/8568#issuecomment-345931081.  One issue on the main repository is more than enough as many of these notifications go out to thousands of people.

**Comment by mdkshuvo** [comment]
Yes, I have got the solution to run the app. If you have no _package.json_ on your project, create a _package.json_ on your project's root directory. Code is

_{
  "name": "yourProjectname",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "meteor-node-stubs": "^0.3.2"
  }
}_
